name: 🌟 Feature request
description: Request for more feature to be added
title: '[Feature Request]: '
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: If you have a solution in mind, please describe it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: true
  - type: dropdown
    id: accomplish_with_exist_API
    attributes:
      label: Accomplish this feature with existing API
      description: Can we accomplish this feature with existing API?
      options:
        - 'yes'
        - 'no'
    validations:
      required: true
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
